# Site settings
title: Learn Magni and ROS
email: jrlandau@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  An open source getting started guide for developers interested in robotics.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
github_username:  UbiquityRobotics
twitter_username:

# Build settings
markdown: kramdown
permalink: pretty

#gems:
#- jekyll-sitemap
